# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    # {id: 0, size: 0.24, name: tag_0},
    # {id: 1, size: 0.24, name: tag_1},
    # {id: 2, size: 0.24, name: tag_2},
    # {id: 3, size: 0.24, name: tag_3},
    # {id: 4, size: 0.32, name: tag_4},
    # {id: 5, size: 0.32, name: tag_5},
    # {id: 6, size: 0.48, name: tag_6},
    # {id: 7, size: 0.56, name: tag_7},
    {id: 8, size: 0.6, name: tag_16}
    # {id: 22, size: 0.09, name: tag_22}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'my_bundle_2m',
      layout:
        [
          {id: 4, size: 0.04, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 6, size: 0.24, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 3, size: 0.4, x: 0.175, y: -0.5497, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 2, size: 0.4, x: 0.175, y: 0.5499, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 1, size: 0.4, x: -0.425, y: 0.0, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000}
        ]
    }
  ]

  # [
  #   {
  #     name: 'my_bundle',
  #     layout:
  #       [
  #         {id: 9, size: 0.015, x: 0.0, y: 0.066, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 10, size: 0.015, x: 0.066, y: -0.0, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 11, size: 0.015, x: 0.0, y: -0.066, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 12, size: 0.015, x: -0.066, y: -0.0, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 6, size: 0.01, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 5, size: 0.058, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 4, size: 0.029, x: -0.0724, y: -0.0724, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 3, size: 0.029, x: 0.0724, y: -0.0724, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 2, size: 0.029, x: 0.0724, y: 0.0724, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
  #         {id: 1, size: 0.029, x: -0.0724, y: 0.0724, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000}
  #       ]
  #   }
  # ]

    # {
    #   name: 'my_bundle_a0',
    #   layout:
    #     [
    #       {id: 9, size: 0.06, x: 0.0, y: 0.21, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 10, size: 0.06, x: 0.21, y: -0.0, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 11, size: 0.06, x: 0.0, y: -0.21, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 12, size: 0.06, x: -0.066, y: -0.0, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 6, size: 0.0312, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 5, size: 0.18, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 4, size: 0.15, x: -0.275, y: -0.275, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 3, size: 0.15, x: 0.275, y: -0.275, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 2, size: 0.15, x: 0.275, y: 0.275, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 1, size: 0.15, x: -0.275, y: 0.275, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000}
    #     ]
    # }