%YAML:1.0
---
aruco_bc_dict: ARUCO_MIP_36h12
aruco_bc_nmarkers: 6
aruco_bc_mInfoType: 1
aruco_bc_markers:
   - { id:3, corners:[
        [ -0.1, 0.35, 0. ], [ 0.1, 0.35, 0. ],
        [ 0.1, 0.15, 0. ], [ -0.1, 0.15, 0. ] ] }
   - { id:4, corners:[
        [ 0.15, 0.1, 0. ], [ 0.35, 0.1, 0. ],
        [ 0.35, -0.1, 0. ], [ 0.15, -0.1, 0. ] ] }
   - { id:5, corners:[
        [ 0.048, 0.112, 0. ], [ 0.112, 0.112, 0. ],
        [ 0.112, 0.048, 0. ], [ 0.048, 0.048, 0. ] ] }
   - { id:7, corners:[
        [ 0.048, -0.048, 0. ], [ 0.112, -0.048, 0. ],
        [ 0.112, -0.112, 0. ], [ 0.048, -0.112, 0. ] ] }
   - { id:8, corners:[
        [ -0.112, -0.048, 0. ], [ -0.048, -0.048, 0. ],
        [ -0.048, -0.112, 0. ], [ -0.112, -0.112, 0. ] ] }
   - { id:9, corners:[
        [ -0.112, 0.112, 0. ], [ -0.048, 0.112, 0. ],
        [ -0.048, 0.048, 0. ], [ -0.112, 0.048, 0. ] ] }
